export const RECOMMEND_START =  "RECOMMEND_INIT";
export const RECOMMEND_SUCCESS =  "RECOMMEND_SUCESS";
export const RECOMMEND_FAILURE =  "RECOMMEND_FAILURE";
export const FETCH_ANIMES_SUCCESS = 'FETCH_ANIMES_SUCCESS';
export const FETCH_ANIMES_FAILURE = 'FETCH_ANIMES_FAILURE';
export const FETCH_ANIMES_START = 'FETCH_ANIMES_START';