export const SEARCH_FETCH_START = "SEARCH_FETCH_START";
export const SEARCH_FETCH_SUCESS = "SEARCH_FETCH_SUCESS";
export const SEARCH_FETCH_FIALURE = "SEARCH_FETCH_FIALURE";
export const SEARCH_WORD_START = "SEARCH_WORD_START";
export const SEARCH_WORD_FAILURE = "SEARCH_WORD_FAILURE";